# Generated by Django 5.2.8 on 2025-11-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('playbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('block_ip', 'Block IP'), ('send_alert', 'Send Alert'), ('log_event', 'Log Event')], max_length=50)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.playbook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playbook')),
            ],
        ),
    ]
