# Generated by Django 5.2.8 on 2025-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='severity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
