# Generated by Django 5.2.8 on 2025-11-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventlog_message_eventlog_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventlog'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playbook'),
        ),
    ]
